spring:
  config:
    activate:
      on-profile: local
    import:
      classpath:/application-aws.yml

  datasource:
    url: jdbc:postgresql://localhost:5432/lovebird
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 1MB
      max-file-size: 100MB
      max-request-size: 100MB

  logging.level:
    org:
      hibernate:
        SQL: debug
        type: trace

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_Secret}
            scope: openid,profile,email

          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Kakao
            scope: openid,profile_nickname,account_email

        provider:
          kakao:
            issuer-uri: https://kauth.kakao.com
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  cloud:
    openfeign:
      client:
        config:
          appleAuthClient:
            connect-timeout: 3
            read-timeout: 1

apple:
  auth:
    token-url: https://appleid.apple.com/auth/token
    public-key-url: https://appleid.apple.com/auth/keys
  redirect-uri: ${APPLE_REDIRECT_URL}
  iss: https://appleid.apple.com
  aud: ${APPLE_CLIENT_ID}
  team-id: ${APPLE_TEAM_ID}
  key:
    id: ${APPLE_KEY_ID}
    path: classpath:/apple/AuthKey_${APPLE_KEY_ID}.p8

jwt:
  access-header: Authorization
  refresh-header: Refresh
  secret: lovebirdwoodaegelovebirdwoodaegelovebirdwoodaegelovebirdwoodaegelovebirdwoodaegelovebirdwoodaege

cloud:
  aws:
    region:
      static:
        ap-northeast-2
    stack:
      auto:
        false