spring:
  config:
    activate:
      on-profile: local
    import:
      classpath:/application-aws.yml

  datasource:
    url: jdbc:h2:mem:wooda
    username: user
    password: password
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 1MB
      max-file-size: 100MB
      max-request-size: 100MB

  logging.level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

cloud:
  aws:
    region:
      static:
        ap-northeast-2
    stack:
      auto:
        false