spring:
  config:
    activate:
      on-profile: local
    import:
      classpath:/application-aws.yml

  datasource:
    url: jdbc:postgresql://localhost:5432/lovebird
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 1MB
      max-file-size: 100MB
      max-request-size: 100MB

  logging.level:
    org:
      hibernate:
        SQL: debug
        type: trace

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "${GOOGLE_CLIENT_ID}"
            client-secret: "${GOOGLE_CLIENT_Secret}"
            scope: profile,email

jwt:
  access-header: Authorization
  refresh-header: Refresh
  secret: lovebirdwoodaegelovebirdwoodaegelovebirdwoodaegelovebirdwoodaegelovebirdwoodaegelovebirdwoodaege

cloud:
  aws:
    region:
      static:
        ap-northeast-2
    stack:
      auto:
        false